### ISSUE TITLE
Bracket CSS breaks on mobile

### ISSUE THREAD

**Issue by auryn-macmillan** [Firstbloodio/BITS-page#48]
When the page switches to mobile, the CSS breaks.
**At >=981px**
![image](https://user-images.githubusercontent.com/8453294/27014863-84b20128-4f44-11e7-80f3-898fa56a9e3a.png)

**At <=980px.**
![image](https://user-images.githubusercontent.com/8453294/27014870-bc6ff336-4f44-11e7-951c-5fffc9fff4c0.png)

**Comment by JasonMcz** [comment]
Okay I am gonna try to push some changes to fix.
