### ISSUE TITLE
Floating Footer

### ISSUE THREAD

**Issue by auryn-macmillan** [Firstbloodio/BITS-page#49]
We need to create a floating footer where we can insert sponsor logos.

The footer should be attached to the bottom of the window in the same way the header is attached to the top (always visible).

The logo should link to https://antlionaudio.com (can we get analytics on the clickthroughs?)

![image](https://user-images.githubusercontent.com/8453294/27014931-f3ff8950-4f45-11e7-9a03-49cedc49be8f.png)

**Comment by JasonMcz** [comment]
Which branch are you pushing these changes to?

**Comment by auryn-macmillan** [comment]
I haven't made any changes for this, so you can push to whichever branch you want.
We should probably just remove the "brackets" branch since it is redundant now.

**Comment by auryn-macmillan** [comment]
No DXRacer logo is needed, just AntlionAudio.

**Comment by auryn-macmillan** [comment]
Also, it does not necessarily have to be a footer. If you think it would fit better somewhere else, I'm happy to work it in wherever. It just needs to be visible at all times on the page.

**Comment by auryn-macmillan** [comment]
On revision, I actually think that this might be a more optimal layout.

![image](https://user-images.githubusercontent.com/8453294/27140460-f08c9716-5168-11e7-836c-3b1a5b341432.png)

When the webpage scales responsively, the `BLOOD IN THE STREETS™` text in the should change to `BITS™` to save space.

**Comment by JasonMcz** [comment]
I dont like that layout because one it's not that notable secondly it doesn't say what our relationship is with Antlion. Let's make a section for sponsor logos like what we did on FB.io

**Comment by auryn-macmillan** [comment]
I'm cool with that, the only thing is that we need to find a way to make sure it's always visible.

**Comment by goofra** [comment]
Hey guys - jumping in on this one. 

If we're okay with removing the legal disclaimer out of the current floater position (and placing it somewhere on the bottom - I know Dan might not agree, but honestly, I am YET to se a page that has a disclaimer written as clearly as we do), we can use that same spot for sponsor logos.

If not, we should create another floater on the bottom (not a fan, but hey). 

@JasonMcz : our FB page only displays logos, no extra description. Is just putting "sponsors" next to these logos okay?

**Comment by auryn-macmillan** [comment]
Check [this commit guys](https://github.com/Firstbloodio/BITS-page/commit/2f3530cfabb3ce62c53478df4fbd09682da74063), everything is working well except the AntlionAudio image is not clickable for some reason.

@JasonMcz happy for you to move things around if you don't like this layout, I just wanted to put it into code. Do you know how to make the image clickable? I guess it must be inheriting `pointer-events: none;` from somewhere, but I can't figure out where from/how to reverse it. `pointer-events; auto;` did not work when I did it inline with the rest of the logo's style.
